### ISSUE TITLE
Creating/Opening A Database With Path

### ISSUE THREAD

**Issue by tengkuizdihar** [ex0dus-0x/microkv#17]
Right now I'm struggling with opening a database that doesn't end with `.kv`. I propose to create a new function like

```
pub fn open_with_path<S: AsRef<str>>(path_to_kv: PathBuf) -> Result<Self>
```

For example, path to KV can be `/home/user/path/dontcare/keyvaluestore.my`. This will result in a more generic way of opening the kv store and easier way to pass the path argument from a file selector (for example).

**Comment by plainerman** [comment]
Hey, you immediately closed this issue. Is this something you don't want to see anymore? Or have you found a solution already?

**Comment by tengkuizdihar** [comment]
Hello, sorry for the inconvenience, I was trying to use microkv for my personal project but I find it isn't suitable for my usecase/ The deal breaker is because microkv loads the entire store to memory (?) upon opening the DB.

But regarding this issue, I think my suggestion would be a nice to have. Simply because of its embedded nature, I would like to add some personal touch to the file extension of the store.

**Comment by plainerman** [comment]
No problem at all :)

Yes, you are right. Microkv is like a glorified dictionary that can be stored securely in a file. But whenever you want to access the data, you must load the complete file (and thus the complete dictionary into memory). 

Thank you for your suggestion.
