### ISSUE TITLE
unused type parameter for `exists`

### ISSUE THREAD

**Issue by ggutoski** [ex0dus-0x/microkv#6]
https://github.com/ex0dus-0x/microkv/blob/610cdee922a7634f1bbc8382ea38246c8ee33d7d/src/kv.rs#L307-L314

Seems that the type parameter `K` is not actually used in `exists`.  The compiler cannot infer the type for `K`, so I must add an explicit type annotation in order to call `exists`.

**Comment by ex0dus-0x** [comment]
Updated, thanks!
