### ISSUE TITLE
`put` should take `&V` instead of `V`

### ISSUE THREAD

**Issue by ggutoski** [ex0dus-0x/microkv#7]
https://github.com/ex0dus-0x/microkv/blob/610cdee922a7634f1bbc8382ea38246c8ee33d7d/src/kv.rs#L230

The only use of `_value` is to pass a reference to `bincode::serialize`.  Thus, `_value` should be of type `&V` instead of `V`.  The way it is now: if your caller has only a reference then you force your caller to make an unnecessary clone into `_value` in order to call `put`.

**Comment by ex0dus-0x** [comment]
Updated, thanks!
